### PR TITLE
72 fix test coverage connects to #105 connects to #72

### LINKED ISSUE #105: fix env testing issues
user model not filling out correctly in test

### PR DESCRIPTION
**Pull request by HoffsMH**
This does not completely close #105 

this pr should bring us up in coverage

### CODE REVIEW

File: spec/controllers/businesses_controller_spec.rb [hunk 1]
```diff
@@ -0,0 +1,17 @@
+require 'rails_helper'
+
+RSpec.describe BusinessesController, type: :controller do
+  describe 'POST #create' do
+    context 'parameters are invalid' do
+      it 'redirects to new with a flash error' do
+        user = create(:user)
+        session[:user_id] = user.id
+        business = Business.new()
```
Comment (7hoenix) [inline spec/controllers/businesses_controller_spec.rb]: Why do we need this line?

File: app/models/user.rb [hunk 2]
```diff
@@ -20,7 +20,10 @@ def self.find_or_create_by_oauth(oauth)
     user.image_url = oauth.info.image
     user.token = oauth.credentials.token
     user.github = oauth.info.urls.GitHub
-    user.location = Octokit.user( user.nickname).location
+    if ENV['RAILS_ENV'] != 'test'
+      user.location = Octokit.user( user.nickname).location
+    end
```
Comment (7hoenix) [inline app/models/user.rb:25]: Are we sure that we aren't going to need nickname sometime in the future for a test?

File: app/controllers/watchlist_controller.rb [hunk 3]
```diff
@@ -27,6 +29,10 @@ def update
     end
   end
```
Comment (7hoenix) [inline app/controllers/watchlist_controller.rb:30]: Need a space here.

File: app/controllers/watchlist_controller.rb [hunk 4]
```diff
@@ -27,6 +29,10 @@ def update
...
   def index
-    redirect_to profile_path(current_user)
+    if session[:watchlist]
+      @watchlist = Job.where(id: session[:watchlist])
+    else
+      redirect_to profile_path(current_user)
```
Comment (7hoenix) [inline app/controllers/watchlist_controller.rb]: Redirect to profile path should be redirect to root.

File: spec/controllers/users_controller_spec.rb [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+        get :show
+
+        expect(response).to redirect_to(root_path)
+      end
+    end
+  end
+
+  describe 'post #update' do
+    context 'when given tags' do
+      it 'attaches thos tags to the user' do
```
Comment (7hoenix) [inline spec/controllers/users_controller_spec.rb]: Those

File: spec/controllers/users_controller_spec.rb [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+        user = create(:user)
+        session[:user_id] = user.id
+
+        tag1 =TagName.create(name: "first tag", color: "color1")
```
Comment (7hoenix) [inline spec/controllers/users_controller_spec.rb]: = TagName

File: spec/features/unauthenticated_users_feature_spec.rb [hunk 7]
```diff
@@ -4,17 +4,31 @@
...
-      expect(page).to have_content("Jr dev")
+      expect(page).to have_content(job.title)
     end
 
     scenario "can view an individual job" do
-      create(:job)
-      visit "/jobs"
-      click_on "Jr dev"
-      expect(page).to have_content("Write some code")
+      job =create(:job)
```
Comment (7hoenix) [inline spec/features/unauthenticated_users_feature_spec.rb]: = create

File: spec/features/unauthenticated_users_feature_spec.rb [hunk 8]
```diff
@@ -4,17 +4,31 @@
...
+      visit "/jobs/#{job.id}"
+      expect(page).to have_content(job.description)
+    end
+
+    scenario "can view an individual job" do
+      job =create(:job)
```
Comment (7hoenix) [inline spec/features/unauthenticated_users_feature_spec.rb]: = create

File: spec/features/unauthenticated_users_feature_spec.rb [hunk 9]
```diff
@@ -4,17 +4,31 @@
...
+      visit "/jobs/"
```
Comment (7hoenix) [inline spec/features/unauthenticated_users_feature_spec.rb]: /jobs

File: spec/models/address_spec.rb [hunk 10]
```diff
@@ -29,5 +29,19 @@
 
       expect(address).to_not be_valid
     end
+
+    it "can have a unit" do
+      address = build(:address, unit: "unit")
+
+      expect(address).to  be_valid
```
Comment (7hoenix) [inline spec/models/address_spec.rb]: to be_valid

File: spec/models/address_spec.rb [hunk 11]
```diff
@@ -29,5 +29,19 @@
...
+      expect(address.full_address).to include("unit")
+    end
+
+    it "doesn't have to have a unit" do
+      address = build(:address, unit: nil)
+
+      expect(address).to  be_valid
```
Comment (7hoenix) [inline spec/models/address_spec.rb]: to be_valid

File: spec/models/job_spec.rb [hunk 12]
```diff
@@ -10,18 +10,29 @@
...
-    
+
     it "is invalid without a description" do
       @job.description = nil
-      
+
       expect(@job).to be_invalid
     end
+
+    it "attach a number of  tags to itself" do
```
Comment (7hoenix) [inline spec/models/job_spec.rb]: attaches

File: spec/models/job_spec.rb [hunk 13]
```diff
@@ -10,18 +10,29 @@
...
+
+      tag1 =TagName.create(name: "first tag", color: "color1")
```
Comment (7hoenix) [inline spec/models/job_spec.rb]: = TagName

File: spec/spec_helper.rb [hunk 14]
```diff
@@ -10,7 +10,7 @@
 
 SimpleCov.start
 
-Coveralls.wear!
+# Coveralls.wear!
```
Comment (7hoenix) [inline spec/spec_helper.rb]: Uncomment
