### PR TITLE
83 fix user test closes #83 closes #91 closes #74 connects to #89

### LINKED ISSUE #74: program seed data
now that we are omniauth we are in a better position make seed programaticly 

we intend to use faker to help with this

### LINKED ISSUE #83: fix broken test associated with users
we broke alot of user test when we implemented
oauth

we need to change user model and fix the test

connects to #54

### LINKED ISSUE #91: add tag_names
we want there to be a discrete list of available tags when attaching tags to users and jobs so we need a tag_name table to hold a list of available tags

### PR DESCRIPTION
**Pull request by HoffsMH**
this test is a branch of of 91 add tag names which is a branch of #89 make site admin

Seeds are now made

Tag_name model now implemented

test now cleaned up and passing

this pull request should close 89 and 91

### CODE REVIEW

File: spec/features/user_visits_a_business_spec.rb [hunk 1]
```diff
@@ -1,26 +1,20 @@
 require "rails_helper"
-
-def log_in
-  visit "/login"
-  fill_in("session[email]", with: @user.email)
-  fill_in("session[password]", with: @user.password)
-  click_button "Login"
-end
+require 'pry'
```
Comment (7hoenix) [inline spec/features/user_visits_a_business_spec.rb:2]: Let's remove this.

File: spec/spec_helper.rb [hunk 2]
```diff
@@ -1,8 +1,19 @@
...
 require "mocha"
+require 'omniauth'
+require 'capybara/rspec'
+
 Coveralls.wear!
 
+
+module IntegrationSpecHelper
+  def login_with_oauth(service = :github)
+    visit "/auth/#{service}"
```
Comment (7hoenix) [inline spec/spec_helper.rb:12]: Is this actually going to hit the github api???

If so we can't merge this or else we are going to get throttled by Github after an hour of TDD.
